server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8998/eureka/

spring:
  application:
    name: Order-Service
  profiles:
    active: dev
  main:
    banner-mode: off #turn off spring boot banner
  data:
    mongodb:
      uri: mongodb+srv://ashaselvaraj:UbV8wdfusAJzq7J1@ashaselvarajmongodb.bdqzbab.mongodb.net/orderdb
      host: ashaselvarajmongodb.bdqzbab.mongodb.net
      database: orderdb #created by mongodb during runtime
      repositories:
        enabled: true
